version: '3'

tasks:
  db-client:
    cmds:
      - rm ./db
      - go run github.com/steebchen/prisma-client-go generate --schema ./ibs3/prisma/schema.prisma

  init:
    cmds:
      - git submodule init
      - git submodule update
      - go get ./...
      - go get github.com/oddinvictus/pinda/db
      - task db-client

  run:
    cmds:
      - air
